manifest:
  remotes:
    - name: LairdCellular
      url-base: git@git.devops.rfpros.com:cp_cellular
    - name: LairdProdEng
      url-base: git@git.devops.rfpros.com:prod_eng

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: laird/hl7800_zephyr_2.3.x
      remote: LairdCellular
      import: true
    - name: zephyr-hal-lairdconnectivity
      path: zephyr/ext/hal/lairdconnectivity
      revision: 1c357f06c6f79515930743e94a94855dd997c679
      remote: LairdCellular
    - name: zephyr_boards
      path: zephyr/boards/arm
      revision: master
      remote: LairdProdEng
    - name: zephyr_lib
      path: modules/zephyr_lib
      revision: master
      remote: LairdProdEng
  self:
    path: pinnacle_firmware
