#ifndef CONFIG_H
#define CONFIG_H

#define DEFAULT_LED_ON_TIME_FOR_1_SECOND_BLINK K_MSEC(100)
#define DEFAULT_LED_OFF_TIME_FOR_1_SECOND_BLINK K_MSEC(900)

#define BUSY_WAIT_TIME_SECONDS 5
#define BUSY_WAIT_TIME (BUSY_WAIT_TIME_SECONDS * 1000000)
#define SLEEP_TIME_SECONDS 60

#endif